In [1]:
import math
from sklearn.feature_extraction.text import TfidfVectorizer

doc=['AI is amazing', 'AI is changing world', 'Machine learning is amazing']
tfidf=TfidfVectorizer()
result=tfidf.fit_transform(doc)
print(tfidf.get_feature_names_out())
print(result.toarray())

['ai' 'amazing' 'changing' 'is' 'learning' 'machine' 'world']
[[0.61980538 0.61980538 0.         0.48133417 0.         0.
  0.        ]
 [0.44451431 0.         0.5844829  0.34520502 0.         0.
  0.5844829 ]
 [0.         0.44451431 0.         0.34520502 0.5844829  0.5844829
  0.        ]]

In [2]:
import math
from sklearn.feature_extraction.text import TfidfVectorizer

doc=['AI is amazing', 'AI is changing world', 'Machine learning is amazing']
tfidf=TfidfVectorizer()
result=tfidf.fit_transform(doc)
print(tfidf.get_feature_names_out())
print(result.toarray())

['ai' 'amazing' 'changing' 'is' 'learning' 'machine' 'world']
[[0.61980538 0.61980538 0.         0.48133417 0.         0.
  0.        ]
 [0.44451431 0.         0.5844829  0.34520502 0.         0.
  0.5844829 ]
 [0.         0.44451431 0.         0.34520502 0.5844829  0.5844829
  0.        ]]

In [3]:
import nltk

In [8]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\91745\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

In [9]:
from nltk.tokenize import word_tokenize

In [10]:
from nltk.tokenize import sent_tokenize
text = '''Characters like periods, exclamation point and newline characters are sued to seperate the sentence
but one drawback with split method that we can only use one seperator at a time!
so sentence tokenization wont be foolproof with split() method'''
result = sent_tokenize(text)
print(result)

['Characters like periods, exclamation point and newline characters are sued to seperate the sentence\nbut one drawback with split method that we can only use one seperator at a time!', 'so sentence tokenization wont be foolproof with split() method']

In [14]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\91745\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\91745\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [18]:
text= """ This is my AI ML internship practice session. Today is the 7th day of my internship """
stop_words=set(stopwords.words('english'))
word_tokens= word_tokenize(text)
filtered_sentence=[]
for w in word_tokens:
    if w not in stop_words:
        if w not in stop_words:
            filtered_sentence.append(w)
print(filtered_sentence)

['This', 'AI', 'ML', 'internship', 'practice', 'session', '.', 'Today', '7th', 'day', 'internship']

In [19]:
from nltk.stem.snowball import SnowballStemmer
stemmer = SnowballStemmer(language= 'english')
word = 'civilization'
stemmer.stem(word)

'civil'

In [21]:
import nltk
from nltk.stem import PorterStemmer, WordNetLemmatizer

# Download WordNet (only once)
nltk.download('wordnet')
nltk.download('omw-1.4')

porter = PorterStemmer()
lemmatizer = WordNetLemmatizer()

print(f"""
Word: better
Stemming: {porter.stem('better')}
Lemmatization: {lemmatizer.lemmatize('better', pos='a')}
""")

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\91745\AppData\Roaming\nltk_data...
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\91745\AppData\Roaming\nltk_data...

Word: better
Stemming: better
Lemmatization: good

In [1]:
import pandas as pd 
messages=pd.read_csv('./Spam.csv',sep=',',names=['label','message'],skiprows=1)
messages.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [2]:
messages.describe()

       label                 message
count   5572                    5572
unique     2                    5157
top      ham  Sorry, I'll call later
freq    4825                      30

In [3]:
messages['length']=messages['message'].apply(len)

In [4]:
messages.head()

  label                                            message  length
0   ham  Go until jurong point, crazy.. Available only ...     111
1   ham                      Ok lar... Joking wif u oni...      29
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...     155
3   ham  U dun say so early hor... U c already then say...      49
4   ham  Nah I don't think he goes to usf, he lives aro...      61

In [10]:
import string

In [11]:
#NLP - Stopwords removing - Text pre-processing 
from nltk.corpus import stopwords
stopwords.words('english') 
def text_process(mess):
    nopunc = [char for char in mess if char not in string.punctuation] 
    nopunc = ''.join(nopunc) 
    return [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]

In [12]:
messages.head()

  label                                            message  length
0   ham  Go until jurong point, crazy.. Available only ...     111
1   ham                      Ok lar... Joking wif u oni...      29
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...     155
3   ham  U dun say so early hor... U c already then say...      49
4   ham  Nah I don't think he goes to usf, he lives aro...      61

In [13]:
messages['message'].head().apply(text_process)

0    [Go, jurong, point, crazy, Available, bugis, n...
1                       [Ok, lar, Joking, wif, u, oni]
2    [Free, entry, 2, wkly, comp, win, FA, Cup, fin...
3        [U, dun, say, early, hor, U, c, already, say]
4    [Nah, dont, think, goes, usf, lives, around, t...
Name: message, dtype: object

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

In [16]:
bow_transformer = CountVectorizer(analyzer=text_process).fit(messages['message'])

In [ ]:
print(len(bow_transformer.vocabulary_))

11422

In [26]:
bow4 = bow_transformer.transform([messages['message'][3]])
print(bow4)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 7 stored elements and shape (1, 11422)>
  Coords	Values
  (0, 4066)	2
  (0, 4627)	1
  (0, 5258)	1
  (0, 6201)	1
  (0, 6219)	1
  (0, 7183)	1
  (0, 9551)	2

In [22]:
message_bow = bow_transformer.transform(messages['message'])
print('Shape of Sparse Matrix: ', message_bow.shape)
print('Amount of Non-Zero occurences: ', message_bow.nnz)
print('Sparsity: %.2f%%' % (100.0 * message_bow.nnz / (message_bow.shape[0] * message_bow.shape[1])))

Shape of Sparse Matrix:  (5572, 11422)
Amount of Non-Zero occurences:  50500
Sparsity: 0.08%

In [27]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer().fit(message_bow)
tfidf4 = tfidf_transformer.transform(bow4)
print(tfidf4)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 7 stored elements and shape (1, 11422)>
  Coords	Values
  (0, 4066)	0.4083258993338407
  (0, 4627)	0.2661980190608719
  (0, 5258)	0.2972995740586873
  (0, 6201)	0.2995379972369742
  (0, 6219)	0.31872168929491496
  (0, 7183)	0.4389365653379858
  (0, 9551)	0.5385626262927565

In [33]:
from sklearn.feature_extraction.text import CountVectorizer

bow_transformer = CountVectorizer(analyzer=text_process)

messages_bow = bow_transformer.fit_transform(messages['message'])

In [34]:
messages_tfidf = tfidf_transformer.transform(messages_bow) 
print(messages_tfidf.shape)
from sklearn.naive_bayes import MultinomialNB  
spam_detect_model = MultinomialNB() # model creation 
spam_detect_model.fit(messages_tfidf, messages['label']) # training 
from sklearn.metrics import classification_report  # model evl.
all_predictions =  spam_detect_model.predict(messages_tfidf) 
print(all_predictions)  
print(classification_report(messages['label'], all_predictions))
 # model testing

(5572, 11422)
['ham' 'ham' 'spam' ... 'ham' 'ham' 'ham']
              precision    recall  f1-score   support

         ham       0.98      1.00      0.99      4825
        spam       1.00      0.85      0.92       747

    accuracy                           0.98      5572
   macro avg       0.99      0.92      0.95      5572
weighted avg       0.98      0.98      0.98      5572

In [1]:
import tensorflow as tf 
from tensorflow.keras.datasets import imdb 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import SimpleRNN
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing import sequence
tf.random.set_seed(7)

In [4]:
top_words = 500
(X_train,y_train),(X_test,y_test) = imdb.load_data(num_words=top_words)

Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/imdb.npz
17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 187s 11us/step

In [ ]:
max_review_length = 500
X_train = sequence.pad_sequences(X_train, maxlen=max_review_length)
X_test = sequence.pad_sequences(X_test, maxlen=max_review_length)

In [14]:
embedding_vecor_length = 32
model=Sequential()
model.add(Embedding(top_words, embedding_vecor_length, input_shape=(max_review_length,)))
model.add(SimpleRNN(100))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=3, batch_size=64)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ (None, 5000, 32)       │        16,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ (None, 100)            │        13,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 29,401 (114.85 KB)

 Trainable params: 29,401 (114.85 KB)

 Non-trainable params: 0 (0.00 B)

None
Epoch 1/3
391/391 ━━━━━━━━━━━━━━━━━━━━ 1692s 4s/step - accuracy: 0.5422 - loss: 0.6900 - val_accuracy: 0.5770 - val_loss: 0.6746
Epoch 2/3
391/391 ━━━━━━━━━━━━━━━━━━━━ 2718s 7s/step - accuracy: 0.6528 - loss: 0.6143 - val_accuracy: 0.7305 - val_loss: 0.5395
Epoch 3/3
391/391 ━━━━━━━━━━━━━━━━━━━━ 1801s 5s/step - accuracy: 0.7417 - loss: 0.5182 - val_accuracy: 0.7411 - val_loss: 0.5154

In [15]:
scores = model.evaluate(X_test, y_test, verbose=0)
print("Accuracy: %.2f%%" % (scores[1]*100))

Accuracy: 74.11%